#
#  Copyright (c) https://github.com/gOOvER/own-pterodactyl-images/blob/main/LICENSE
#

name: Bot Builder

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  push:
    name: "Docker Builder"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: DisBot-Helper-Bot/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/disbotdevelopment/disbot-helper:${{ github.run_number }}
            ghcr.io/disbotdevelopment/disbot-helper:latest